### ISSUE TITLE
ActionTextを使用したリッチテキストエディタに画像が表示されない件について

### ISSUE THREAD

**Issue by sugimotokaz** [sugimotokaz/oshiopen#186]
## 解決したいこと・達成したいものについて
article/edit.html.erbのリッチテキストエディタ内で、既に登録されている画像を表示したいです。

article/edit.html.erbのリッチテキストエディタ内に既に登録されている画像が表示されず、「Add a caption」とのみ表示されます。
一緒に保存したテキストは問題なく表示されます。
[![Image from Gyazo](https://i.gyazo.com/50043096b998964212a4a7d359db7d46.png)](https://gyazo.com/50043096b998964212a4a7d359db7d46)  

new.html.erbやedit.html.erbで新規に画像を貼り付けると画像は表示されます。

##### new.html.erb
[![Image from Gyazo](https://i.gyazo.com/b3589b68f89863d1190fbb79058936aa.png)](https://gyazo.com/b3589b68f89863d1190fbb79058936aa). 

##### edit.html.erbに追加で画像を貼り付けた時
[![Image from Gyazo](https://i.gyazo.com/5f969d7d1cef109c1b8b3ccbca0d4c77.gif)](https://gyazo.com/5f969d7d1cef109c1b8b3ccbca0d4c77)
新規で貼り付けた画像は表示されますが、既に登録されていた画像は「Add a caption」とのみ表示されます。
また、この状態で更新したとしても問題なく2枚ともshow.html.erbで表示されます。
[![Image from Gyazo](https://i.gyazo.com/f8ee4dd36ad8fb80b9361490221b13bd.png)](https://gyazo.com/f8ee4dd36ad8fb80b9361490221b13bd). 

画像は新規登録、更新ともに正常に保存され詳細ページには表示されていますが、編集ページのテキストエディタ内でのみ表示がされていません。

## 聞きたいこと・アドバイスが欲しいこと
- なぜ、編集ページのテキストエディタ内でのみ画像が表示されないのか
- どのファイルのどのコードを改善すると良いのか

## 実装の際に参考にした資料等
- ActionTextでのエディタの導入方法
https://plog.kobacchi.com/rails7-action-text-introduced/
上記の記事ではpostモデルですが、articleモデルを使用しています。

- エディタ内で保存した画像の保存先実装方法
https://qiita.com/hmmrjn/items/7cc5e5348755c517458a
- Tailwindを使用しているときのActionTextのデザイン
https://qiita.com/MIDO-ruby7/items/fd2c31ba00d8420cf630

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
リポジトリURL　https://github.com/sugimotokaz/oshiopen

#### 関係していると思うファイル・コード
- articles_controller.rb
[![Image from Gyazo](https://i.gyazo.com/0cd286105d6fa249042db893e4bc2f1e.png)](https://gyazo.com/0cd286105d6fa249042db893e4bc2f1e)
[![Image from Gyazo](https://i.gyazo.com/19ad909e5a6898f96edc437d1023c428.png)](https://gyazo.com/19ad909e5a6898f96edc437d1023c428)

- articles/edit.html.erb
[![Image from Gyazo](https://i.gyazo.com/3d8fcdb81632fa0a16f2e4f4fcda994a.png)](https://gyazo.com/3d8fcdb81632fa0a16f2e4f4fcda994a)
テキストエディタの表示部分は34行目から41行目です。

- app/assets/stylesheets/actiontext.css
- app/views/active_storage/blobs/_blob.html.erb
[![Image from Gyazo](https://i.gyazo.com/491db8d4e29087ac7e271d8c238e14a5.png)](https://gyazo.com/491db8d4e29087ac7e271d8c238e14a5)

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
- articles/edit.html.erbで取得された既に登録されていた画像のURLを、Action TextがURLを画像として解釈していない。

エディタに新規で貼り付けた時のデベロッパーツールのElementsです。
新規に貼り付けたものは下記の２行目に「<img src=」がありますが、
```
<figure contenteditable="false" data-trix-attachment="{&quot;contentType&quot;:&quot;image/jpeg&quot;,&quot;filename&quot;:&quot;IMG_1078.jpeg&quot;,&quot;filesize&quot;:68220,&quot;height&quot;:1646,&quot;sgid&quot;:&quot;eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL215YXBwL0FjdGl2ZVN0b3JhZ2U6OkJsb2IvMTQxP2V4cGlyZXNfaW4iLCJwdXIiOiJhdHRhY2hhYmxlIn19--5d249f8e28cf82ff85b56ddd35e7b4245d0cf9e3&quot;,&quot;url&quot;:&quot;http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTQxLCJwdXIiOiJibG9iX2lkIn19--9ae9292d49e485f1184f38dcc39cbd745c524628/IMG_1078.jpeg&quot;,&quot;width&quot;:1646}" data-trix-content-type="image/jpeg" data-trix-id="21211" data-trix-attributes="{&quot;presentation&quot;:&quot;gallery&quot;}" class="attachment attachment--preview attachment--jpeg" data-trix-mutable="true"><img src="http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTQxLCJwdXIiOiJibG9iX2lkIn19--9ae9292d49e485f1184f38dcc39cbd745c524628/IMG_1078.jpeg" data-trix-mutable="true" width="1646" height="1646" data-trix-store-key="imageElement/21211/http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTQxLCJwdXIiOiJibG9iX2lkIn19--9ae9292d49e485f1184f38dcc39cbd745c524628/IMG_1078.jpeg/325/325"><figcaption class="attachment__caption attachment__caption--editing"><textarea placeholder="Add a caption…" data-trix-mutable="true" class="attachment__caption-editor" style="height: 17px;"></textarea><textarea placeholder="Add a caption…" data-trix-mutable="true" class="attachment__caption-editor trix-autoresize-clone" tabindex="-1"></textarea></figcaption><figcaption class="attachment__caption" style="display: none;"><span class="attachment__name">IMG_1078.jpeg</span> <span class="attachment__size">66.62 KB</span></figcaption><div data-trix-mutable="true" class="attachment__toolbar"><div class="trix-button-row"><span class="trix-button-group trix-button-group--actions"><button title="Remove" data-trix-action="remove" class="trix-button trix-button--remove">Remove</button></span></div><div class="attachment__metadata-container"><span class="attachment__metadata"><span title="IMG_1078.jpeg" class="attachment__name">IMG_1078.jpeg</span><span class="attachment__size">66.62 KB</span></span></div></div></figure>
```
```
<img src="http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTQxLCJwdXIiOiJibG9iX2lkIn19--9ae9292d49e485f1184f38dcc39cbd745c524628/IMG_1078.jpeg" data-trix-mutable="true" width="1646" height="1646" data-trix-store-key="imageElement/21211/http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTQxLCJwdXIiOiJibG9iX2lkIn19--9ae9292d49e485f1184f38dcc39cbd745c524628/IMG_1078.jpeg/325/325">
```
```
<figcaption class="attachment__caption attachment__caption--editing"><textarea placeholder="Add a caption…" data-trix-mutable="true" class="attachment__caption-editor" style="height: 17px;"></textarea><textarea placeholder="Add a caption…" data-trix-mutable="true" class="attachment__caption-editor trix-autoresize-clone" tabindex="-1"></textarea></figcaption>  
```

既に保存された画像のデベロッパーツールのElements(下記)では、「<img src=」が無いため、画像と認識していないと考えました。
```
<figure contenteditable="false" data-trix-attachment="{&quot;content&quot;:&quot;&quot;,&quot;contentType&quot;:&quot;image/jpeg&quot;,&quot;filename&quot;:&quot;IMG_1078.jpeg&quot;,&quot;filesize&quot;:68220,&quot;height&quot;:1646,&quot;previewable&quot;:true,&quot;sgid&quot;:&quot;eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL215YXBwL0FjdGl2ZVN0b3JhZ2U6OkJsb2IvMTM3P2V4cGlyZXNfaW4iLCJwdXIiOiJhdHRhY2hhYmxlIn19--b241f334640a81946f6f6a017ac8795c26a98a93&quot;,&quot;url&quot;:&quot;http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsiZGF0YSI6MTM3LCJwdXIiOiJibG9iX2lkIn19--798e81c67783493c49688a7a4f8100adb380937f/IMG_1078.jpeg&quot;,&quot;width&quot;:1646}" data-trix-content-type="image/jpeg" data-trix-id="18532" data-trix-attributes="{&quot;presentation&quot;:&quot;gallery&quot;}" class="attachment attachment--content attachment--jpeg" data-trix-mutable="true"><figcaption class="attachment__caption attachment__caption--editing" data-trix-placeholder="Add a caption…"><textarea placeholder="Add a caption…" data-trix-mutable="true" class="attachment__caption-editor" style="height: 24px;"></textarea><textarea placeholder="Add a caption…" data-trix-mutable="true" class="attachment__caption-editor trix-autoresize-clone" tabindex="-1"></textarea></figcaption><figcaption class="attachment__caption" data-trix-placeholder="Add a caption…" style="display: none;"></figcaption><div data-trix-mutable="true" class="attachment__toolbar"><div class="trix-button-row"><span class="trix-button-group trix-button-group--actions"><button title="Remove" data-trix-action="remove" class="trix-button trix-button--remove">Remove</button></span></div><div class="attachment__metadata-container"><span class="attachment__metadata"><span title="IMG_1078.jpeg" class="attachment__name">IMG_1078.jpeg</span><span class="attachment__size">66.62 KB</span></span></div></div></figure>
```
```
<figcaption class="attachment__caption" data-trix-placeholder="Add a caption…"></figcaption>. 
```

そこでapp/views/active_storage/blobs/_blob.html.erbの下記部分がedit.html.erbページではfalseを返しているのだと考えました。
```
<% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
<% end %>
```
chatGPTに確認方法を聞き、下記をedit.html.erbのエディタの下に記述し、画像が表示可能か確認してみました。
```
<div class="mb-4">
    <% @article.content.embeds.each do |attachment| %>
    <p>blob.representable? is: <%= attachment.blob.representable? %></p>
    <p>blob metadata: <%= attachment.blob.metadata %></p>
    <% end %>
</div>
```

[![Image from Gyazo](https://i.gyazo.com/1528e7f523f3df386e7a847a2b0dcd1a.png)](https://gyazo.com/1528e7f523f3df386e7a847a2b0dcd1a)
画像のようにtrueは帰ってきたので、表示自体はできるのだと解釈しました。

## 検証した結果から分かったこと・考えたこと
- エディタ内ではimgタグが生成されない。
- editページにも画像のURLは適切に取得できている。
- ActionTextでは元々、編集ページで保存されている画像は表示できないのではないか

**Comment by Tsuchiya2** [comment]
> ActionTextでは元々、編集ページで保存されている画像は表示できないのではないか

こちらに関してですが、最適な資料を用意できなかったですが、編集ページでも画像の表示はできるものと認識しています。

例：https://youtu.be/4JNDy03d0Uw?si=BtpOAOM7zvjXGzZ5&t=580

カスタマイズなどの記載を加えているように見えたのですが、そもそもカスタマイズする前はどのような状態だったのか、別の同じ環境のアプリケーションで公式ドキュメントを元に技術検証した際に同様の現象が起きるのかなど、現状から離れてそもそもベースで確認&検証してみて事実関係を確認するところから始めてみましょう。

https://railsguides.jp/action_text_overview.html
