### ISSUE TITLE
MVPリリース　レビュー用

### ISSUE THREAD

**Issue by sugimotokaz** [sugimotokaz/oshiopen#70]
## 各種情報
サービス名：推しOPEN
サービスURL：https://secret-castle-37895-e07353d7e3ae.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [X] ユーザー作成
- [X] ログイン機能
- [X] プロフィール設定、編集
- [X] 推し登録、編集
- [X] 投稿一覧機能
- [X] 投稿機能
  - [X] 編集、削除
  - [X] 限定公開機能
- [X] コメント機能、編集、削除

## READMEレビュー時から変更した機能
以下は、issueベースの提出の際にMVPリリースに含めなくても良いといっていただいたものです。
- i18nの導入、日本語対応
- 記事お気に入り機能
- ユーザーお気に入り機能
- 検索機能
- google認証

## サービスイメージがわかるようなスクリーンショット等
- ユーザー登録画面
![image](https://github.com/user-attachments/assets/1f69b51b-30a3-4b69-babf-c8068404ba18)

- ログイン画面
![image](https://github.com/user-attachments/assets/576e48fa-0d87-405c-af99-976e6ffd8b9f)

- マイページ
![image](https://github.com/user-attachments/assets/e498fe92-71c6-4308-ae43-f6ad10801544)

- プロフィール編集画面
![image](https://github.com/user-attachments/assets/720c25e3-eb2e-4ac9-8634-d470678c9fbc)

- 推し登録画面
![image](https://github.com/user-attachments/assets/a11d8714-ef31-46a3-9284-ec665819b77d)

- 記事一覧
![image](https://github.com/user-attachments/assets/6d11f8a0-653f-43c0-ae35-ecc0350c5f91)

- 記事作成ページ
![image](https://github.com/user-attachments/assets/a5b54e37-33ff-4dfd-b68c-b056406755a6)

- 記事編集ページ
![image](https://github.com/user-attachments/assets/c2d1744e-4d73-482c-b2e4-d6237ef883e3)

- 記事詳細ページ
![image](https://github.com/user-attachments/assets/ab7fd570-b962-4e82-ba1d-5c7c2b73f5a9)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下も取り組む =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
